import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar/NavBar";
import ClientOnly from "./components/ClientOly";
import RegirsTerModal from "./components/Modal/RegirsTerModal";
import LoginModal from "./components/Modal/LoginModal";
import getCurrentUser from "../app/action/getCurrentUer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const curentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <RegirsTerModal />
          <LoginModal />
          <NavBar curentUser={curentUser} />
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
